### ISSUE TITLE
[Feature Request] Start on platform screen

### ISSUE THREAD

**Issue by wivelden** [PlayingKarrde/gameOS#166]
Is it possible upon boot to have it start on a chosen platform screen rather than the main screen or is this a Peagsus specific option only?

**Comment by HVR88** [comment]
The current default has the gameOS logo selected which is somewhat intuitive because it's not obvious where the selection is nor can the logo be activated while selected.  

It would be most intuitive to have the first system in the list automatically selected at startup, however I recognize the visual caveats were that to happen without additional changes. Currently, when a system is selected, the gameOS logo becomes dimmer and the grid scrolls upward to partially obscure the header rectangle. Having the logo displayed at its bright/selected appearance and with the full header rectangle unobstructed definitely looks much nicer.

**Comment by PlayingKarrde** [comment]
I think @wivelden is more saying they want to start the theme on the grid view for a specific platform. This isn't really the intention of this theme, although it would technically be possible. I think though I would rather keep it as is since the point of the theme is a general discovery and game hub. There are other themes that might be more suitable to your needs.

@HVR88 you're right this isn't a great user experience. I'll be updating this in the next release.

**Comment by HVR88** [comment]
True, he might have been asking to start within a platform.  I agree, that's definitely not how I'd envision it ever working and adding that option, even if possible, kind of clutters up the settings.

That said, it might be nice to mention a quick and dirty way to modify the source so that @wivelden can et away with it on his own local copy.
